# Generated by Django 4.2.13 on 2024-07-17 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_created=True, auto_now=True, verbose_name="수정일"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_created=True, auto_now_add=True, verbose_name="작성일"
                    ),
                ),
                ("title", models.CharField(max_length=24, verbose_name="제목")),
                ("content", models.CharField(max_length=300, verbose_name="내용")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="posts/%Y%m%d", verbose_name="이미지"
                    ),
                ),
                (
                    "interest",
                    models.IntegerField(default=1000, verbose_name="아이디어 관심도"),
                ),
                ("dibs", models.BooleanField(default=False, verbose_name="찜")),
                (
                    "devtool",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tools.tool",
                        verbose_name="개발툴",
                    ),
                ),
            ],
        ),
    ]
