# Generated by Django 4.2.13 on 2024-07-17 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
        ("ideas", "0002_remove_idea_devtool_alter_idea_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="devtool",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tools.tool",
                verbose_name="개발툴",
            ),
        ),
    ]
