# Generated by Django 4.2.13 on 2024-07-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=24, verbose_name="이름")),
                ("kind", models.CharField(max_length=24, verbose_name="종류")),
                (
                    "tool_content",
                    models.CharField(max_length=300, verbose_name="개발툴 설명"),
                ),
            ],
        ),
    ]
