# Generated by Django 4.2.13 on 2024-07-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("year", models.IntegerField(verbose_name="개봉 연도")),
                ("genre", models.CharField(max_length=50, verbose_name="장르")),
                ("star", models.IntegerField(verbose_name="별점")),
                ("review", models.TextField(verbose_name="리뷰내용")),
                ("director", models.CharField(max_length=50, verbose_name="감독")),
                ("actor", models.CharField(max_length=50, verbose_name="주연배우")),
                ("running", models.IntegerField(verbose_name="러닝타임")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
