# Generated by Django 4.2.13 on 2024-07-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="star",
            field=models.FloatField(verbose_name="별점"),
        ),
    ]
