# Generated by Django 4.2.13 on 2024-07-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_review_star"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="genre",
            field=models.CharField(
                choices=[
                    ("unknown", "미정"),
                    ("action", "액션"),
                    ("animation", "애니메이션"),
                    ("drama", "드라마"),
                    ("romance", "로맨스"),
                    ("mystery", "미스터리"),
                    ("SF", "SF"),
                    ("horror", "호러"),
                    ("criminal", "범죄"),
                ],
                default="unknwon",
                max_length=50,
                verbose_name="장르",
            ),
        ),
    ]
