# Generated by Django 4.2.13 on 2024-07-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_alter_review_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="genre",
            field=models.CharField(
                choices=[
                    ("액션", "액션"),
                    ("애니메이션", "애니메이션"),
                    ("드라마", "드라마"),
                    ("판타지", "판타지"),
                    ("로맨스", "로맨스"),
                    ("미스터리", "미스터리"),
                    ("SF", "SF"),
                    ("호러", "호러"),
                    ("범죄", "범죄"),
                    ("기타", "기타"),
                ],
                default="기타",
                max_length=50,
                verbose_name="장르",
            ),
        ),
    ]
